services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    network_mode: host
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
    environment:
      - UID=0
      - GID=0
      - DELETE_FILE_ON_TRASHCAN=true
